### ISSUE TITLE
Integration into an application

### ISSUE THREAD

**Issue by gszecsenyi** [staD020/png2prg#1]
Hello, is it possible to integrate the output into the application? 
I mean, I start the program, the image appears, and then it switches to my **basic** program that I wrote. 
If there is a way to do this, could you please give me a short example?

Thanks!

**Comment by staD020** [comment]
The default operation of png2prg is to convert the png to a prg to be used in your own applications, but you will need to write the display code yourself, this is also possible in basic.
load the prg, assuming it's koala (multicolor bitmap) and run this basic code:

10 poke53265,59:poke53270,216:poke53272,24:poke53280,0:poke53281,0
20 forato999:poke1024+a,peek(16192+a):poke55296+a,peek(17192+a):next

Mind you, basic is crazy slow, the for-loop to copy the colors will take a while.
It's much faster in assembly, there's a good example here: https://codebase64.org/doku.php?id=base:demo_coding_introduction#bitmap_graphics
